version: '3.9'

services:
    app:
        build: .
        container_name: selenium_parser_app
        volumes:
            - .:/app
        working_dir: /app
        tty: true
        stdin_open: true
        depends_on:
            selenium:
                condition: service_healthy
        networks:
            - parser_net
        environment:
            SELENIUM_HOST: 'http://selenium:4444/wd/hub'

    selenium:
        image: seleniarm/standalone-chromium:latest
        container_name: selenium_parser_selenium
        shm_size: 2g
        ports:
            - "4444:4444"
        environment:
            - SE_NODE_MAX_SESSIONS=5
            - SE_NODE_OVERRIDE_MAX_SESSIONS=true
        networks:
            - parser_net
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
            interval: 5s
            timeout: 2s
            retries: 10

networks:
    parser_net:
        driver: bridge
